# Generated by Django 3.0.4 on 2020-03-31 10:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('onboarding_status', models.IntegerField(choices=[(1, 'NOT_ONBOARDED'), (2, 'ONBOARDED')], default=(1, 'NOT_ONBOARDED'))),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.IntegerField(default=560000)),
                ('availability_status', models.CharField(blank=True, max_length=500, null=True)),
                ('meta', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
