# Generated by Django 3.0.4 on 2020-03-31 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('medical_qual', models.CharField(choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('MD', 'MD'), ('DNB', 'DNB'), ('DGO', 'DGO'), ('MCH', 'MCH'), ('MRCP', 'MRCP'), ('FRCP', 'FRCP'), ('MDS', 'MDS'), ('MS', 'MS')], max_length=10)),
                ('mci', models.IntegerField(unique=True)),
                ('state_authority', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('other_contact', models.CharField(max_length=10, null=True)),
                ('time_pref', models.CharField(choices=[('7AM-11AM', '7AM-11AM'), ('11AM-3PM', '11AM-3PM'), ('3PM-7PM', '3PM-7PM'), ('7PM-11PM', '7PM-11PM'), ('11PM-7AM', '11PM-7AM'), ('Anytime', 'Anytime')], max_length=10)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('organisation_name', models.CharField(max_length=100)),
                ('doctor_type', models.CharField(choices=[('partner', 'partner'), ('volunteer', 'volunteer')], max_length=10)),
                ('duty_hours', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6'), ('>8', '>8'), ('Other', 'Other')], max_length=10)),
                ('onboarding_status', models.CharField(choices=[('succeed', 'succeed'), ('fail', 'fail'), ('rejected', 'rejected'), ('unqualified', 'unqualified'), ('queue', 'queue')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freshdesk_agent_created', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200)),
                ('meta_status', models.CharField(max_length=100)),
            ],
        ),
    ]
